### ISSUE TITLE
How can I send a TCP/HTTP request using this library?

### ISSUE THREAD

**Issue by mynameisbill2** [d-a-v/W5500lwIP#12]
I have connected to the Enthernet using the library following ths example from issues #5 , but I don't know how to send a TCP/HTTP request by this. Could you help me? And thinks for your quickly reponse before!

**Comment by d-a-v** [comment]
You can use examples from esp8266/arduino
https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266HTTPClient/examples

**Comment by mynameisbill2** [comment]
Thinks a lot, it works! Amazing!
