### ISSUE TITLE
How to set static ip?

### ISSUE THREAD

**Issue by darkautism** [d-a-v/W5500lwIP#13]
I have a W5500 module and i wanna emulate a mini router.
But i did not know how to set static ip in w5500.
I notice old discussion tells we can `eth.config(ip, mask, ip, ip);` but with no luck.
``` shell
src\main.cpp: In function 'void setup()':
src\main.cpp:25:7: error: 'using Wiznet5500lwIP = class LwipEthernet<Wiznet5500>' has no member named 'config'
   eth.config(ip, mask, ip, ip);
```
It seems only ESP8266WiFiSTAClass class have config method.

I wrote a sample begin but with no luck, what i missed?

``` cpp
    _netif.ip_addr = ip;
    _netif.gw = gw;
    _netif.netmask = mask;
    _netif.hwaddr_len = sizeof _macAddress;
    memcpy(_netif.hwaddr, _macAddress, sizeof _macAddress);
    netif_add(&_netif, ip, mask, gw, this, netif_init_s, ethernet_input);
    netif_set_up(&_netif);
```

Thanks for the amazing work btw!

**Comment by d-a-v** [comment]
Did you try to use  https://github.com/esp8266/Arduino/pull/6680 instead ?

**Comment by darkautism** [comment]
It's worked! Thanks you!
