### ISSUE TITLE
IRQs: please always consider near-realtime implications

### ISSUE THREAD

**Issue by dok-net** [d-a-v/W5500lwIP#8]
https://github.com/d-a-v/W5500lwIP/blob/9de94714fb20d4b367da7343e6b245064f01fca0/src/utility/lwIPeth.h#L126
This fairly certainly breaks SoftwareSerail RX and anything like it that depends on exact timings. Using `attachScheduledInterrupt()` is the correct, available, use here.

**Comment by d-a-v** [comment]
IRQ currently does not work.
Users will however be free to chose the way of receiving data, by polling or interrupts.
Your notice will be taken into consideration and will be added in documentation when this driver will move into the esp8266 arduino core, eventually.
